FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY . .
RUN go mod tidy -compat=1.25 && \
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o api-gateway ./cmd/api-gateway

FROM alpine:3.18

WORKDIR /root/

COPY --from=builder /app/api-gateway .

EXPOSE 3000

HEALTHCHECK --interval=10s --timeout=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/health || exit 1

ENTRYPOINT ["./api-gateway"]
