FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY . .
RUN go mod tidy -compat=1.25 && \
	CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o connector ./cmd/connector

FROM alpine:3.18

WORKDIR /root/

COPY --from=builder /app/connector .
COPY connector-config.yml .

EXPOSE 1883

ENTRYPOINT ["./connector", "./connector-config.yml"]
