// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/proto/alert.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlertServiceClient is the client API for AlertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertServiceClient interface {
	// CreateThreshold creates a new alert threshold for a device metric.
	CreateThreshold(ctx context.Context, in *CreateThresholdRequest, opts ...grpc.CallOption) (*CreateThresholdResponse, error)
	// GetThresholds retrieves all thresholds for a device or metric.
	GetThresholds(ctx context.Context, in *GetThresholdsRequest, opts ...grpc.CallOption) (*GetThresholdsResponse, error)
	// UpdateThreshold modifies an existing alert threshold.
	UpdateThreshold(ctx context.Context, in *UpdateThresholdRequest, opts ...grpc.CallOption) (*UpdateThresholdResponse, error)
	// DeleteThreshold removes an alert threshold.
	DeleteThreshold(ctx context.Context, in *DeleteThresholdRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// GetActiveAlerts retrieves alerts triggered in the last N seconds (real-time dashboard view).
	GetActiveAlerts(ctx context.Context, in *GetActiveAlertsRequest, opts ...grpc.CallOption) (*GetActiveAlertsResponse, error)
	// QueryAlertHistory retrieves historical alerts within a time range (archive queries).
	QueryAlertHistory(ctx context.Context, in *QueryAlertHistoryRequest, opts ...grpc.CallOption) (AlertService_QueryAlertHistoryClient, error)
	// SilenceAlert silences a specific alert by device and metric for a duration.
	SilenceAlert(ctx context.Context, in *SilenceAlertRequest, opts ...grpc.CallOption) (*SilenceAlertResponse, error)
	// GetSilenceState retrieves active silencing rules for a device.
	GetSilenceState(ctx context.Context, in *GetSilenceStateRequest, opts ...grpc.CallOption) (*GetSilenceStateResponse, error)
	// ClearSilence removes all silencing for a device.
	ClearSilence(ctx context.Context, in *ClearSilenceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// GetAlertStats retrieves aggregated alert statistics (total fired, by severity, etc).
	GetAlertStats(ctx context.Context, in *GetAlertStatsRequest, opts ...grpc.CallOption) (*GetAlertStatsResponse, error)
}

type alertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertServiceClient(cc grpc.ClientConnInterface) AlertServiceClient {
	return &alertServiceClient{cc}
}

func (c *alertServiceClient) CreateThreshold(ctx context.Context, in *CreateThresholdRequest, opts ...grpc.CallOption) (*CreateThresholdResponse, error) {
	out := new(CreateThresholdResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.AlertService/CreateThreshold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) GetThresholds(ctx context.Context, in *GetThresholdsRequest, opts ...grpc.CallOption) (*GetThresholdsResponse, error) {
	out := new(GetThresholdsResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.AlertService/GetThresholds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) UpdateThreshold(ctx context.Context, in *UpdateThresholdRequest, opts ...grpc.CallOption) (*UpdateThresholdResponse, error) {
	out := new(UpdateThresholdResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.AlertService/UpdateThreshold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) DeleteThreshold(ctx context.Context, in *DeleteThresholdRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.AlertService/DeleteThreshold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) GetActiveAlerts(ctx context.Context, in *GetActiveAlertsRequest, opts ...grpc.CallOption) (*GetActiveAlertsResponse, error) {
	out := new(GetActiveAlertsResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.AlertService/GetActiveAlerts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) QueryAlertHistory(ctx context.Context, in *QueryAlertHistoryRequest, opts ...grpc.CallOption) (AlertService_QueryAlertHistoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &AlertService_ServiceDesc.Streams[0], "/fieldpulse.api.AlertService/QueryAlertHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &alertServiceQueryAlertHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AlertService_QueryAlertHistoryClient interface {
	Recv() (*QueryAlertHistoryResponse, error)
	grpc.ClientStream
}

type alertServiceQueryAlertHistoryClient struct {
	grpc.ClientStream
}

func (x *alertServiceQueryAlertHistoryClient) Recv() (*QueryAlertHistoryResponse, error) {
	m := new(QueryAlertHistoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *alertServiceClient) SilenceAlert(ctx context.Context, in *SilenceAlertRequest, opts ...grpc.CallOption) (*SilenceAlertResponse, error) {
	out := new(SilenceAlertResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.AlertService/SilenceAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) GetSilenceState(ctx context.Context, in *GetSilenceStateRequest, opts ...grpc.CallOption) (*GetSilenceStateResponse, error) {
	out := new(GetSilenceStateResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.AlertService/GetSilenceState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) ClearSilence(ctx context.Context, in *ClearSilenceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.AlertService/ClearSilence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) GetAlertStats(ctx context.Context, in *GetAlertStatsRequest, opts ...grpc.CallOption) (*GetAlertStatsResponse, error) {
	out := new(GetAlertStatsResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.AlertService/GetAlertStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertServiceServer is the server API for AlertService service.
// All implementations must embed UnimplementedAlertServiceServer
// for forward compatibility
type AlertServiceServer interface {
	// CreateThreshold creates a new alert threshold for a device metric.
	CreateThreshold(context.Context, *CreateThresholdRequest) (*CreateThresholdResponse, error)
	// GetThresholds retrieves all thresholds for a device or metric.
	GetThresholds(context.Context, *GetThresholdsRequest) (*GetThresholdsResponse, error)
	// UpdateThreshold modifies an existing alert threshold.
	UpdateThreshold(context.Context, *UpdateThresholdRequest) (*UpdateThresholdResponse, error)
	// DeleteThreshold removes an alert threshold.
	DeleteThreshold(context.Context, *DeleteThresholdRequest) (*empty.Empty, error)
	// GetActiveAlerts retrieves alerts triggered in the last N seconds (real-time dashboard view).
	GetActiveAlerts(context.Context, *GetActiveAlertsRequest) (*GetActiveAlertsResponse, error)
	// QueryAlertHistory retrieves historical alerts within a time range (archive queries).
	QueryAlertHistory(*QueryAlertHistoryRequest, AlertService_QueryAlertHistoryServer) error
	// SilenceAlert silences a specific alert by device and metric for a duration.
	SilenceAlert(context.Context, *SilenceAlertRequest) (*SilenceAlertResponse, error)
	// GetSilenceState retrieves active silencing rules for a device.
	GetSilenceState(context.Context, *GetSilenceStateRequest) (*GetSilenceStateResponse, error)
	// ClearSilence removes all silencing for a device.
	ClearSilence(context.Context, *ClearSilenceRequest) (*empty.Empty, error)
	// GetAlertStats retrieves aggregated alert statistics (total fired, by severity, etc).
	GetAlertStats(context.Context, *GetAlertStatsRequest) (*GetAlertStatsResponse, error)
	mustEmbedUnimplementedAlertServiceServer()
}

// UnimplementedAlertServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAlertServiceServer struct {
}

func (UnimplementedAlertServiceServer) CreateThreshold(context.Context, *CreateThresholdRequest) (*CreateThresholdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateThreshold not implemented")
}
func (UnimplementedAlertServiceServer) GetThresholds(context.Context, *GetThresholdsRequest) (*GetThresholdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThresholds not implemented")
}
func (UnimplementedAlertServiceServer) UpdateThreshold(context.Context, *UpdateThresholdRequest) (*UpdateThresholdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateThreshold not implemented")
}
func (UnimplementedAlertServiceServer) DeleteThreshold(context.Context, *DeleteThresholdRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteThreshold not implemented")
}
func (UnimplementedAlertServiceServer) GetActiveAlerts(context.Context, *GetActiveAlertsRequest) (*GetActiveAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveAlerts not implemented")
}
func (UnimplementedAlertServiceServer) QueryAlertHistory(*QueryAlertHistoryRequest, AlertService_QueryAlertHistoryServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryAlertHistory not implemented")
}
func (UnimplementedAlertServiceServer) SilenceAlert(context.Context, *SilenceAlertRequest) (*SilenceAlertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SilenceAlert not implemented")
}
func (UnimplementedAlertServiceServer) GetSilenceState(context.Context, *GetSilenceStateRequest) (*GetSilenceStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSilenceState not implemented")
}
func (UnimplementedAlertServiceServer) ClearSilence(context.Context, *ClearSilenceRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearSilence not implemented")
}
func (UnimplementedAlertServiceServer) GetAlertStats(context.Context, *GetAlertStatsRequest) (*GetAlertStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertStats not implemented")
}
func (UnimplementedAlertServiceServer) mustEmbedUnimplementedAlertServiceServer() {}

// UnsafeAlertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertServiceServer will
// result in compilation errors.
type UnsafeAlertServiceServer interface {
	mustEmbedUnimplementedAlertServiceServer()
}

func RegisterAlertServiceServer(s grpc.ServiceRegistrar, srv AlertServiceServer) {
	s.RegisterService(&AlertService_ServiceDesc, srv)
}

func _AlertService_CreateThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateThresholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).CreateThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.AlertService/CreateThreshold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).CreateThreshold(ctx, req.(*CreateThresholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_GetThresholds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThresholdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).GetThresholds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.AlertService/GetThresholds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).GetThresholds(ctx, req.(*GetThresholdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_UpdateThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateThresholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).UpdateThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.AlertService/UpdateThreshold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).UpdateThreshold(ctx, req.(*UpdateThresholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_DeleteThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteThresholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).DeleteThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.AlertService/DeleteThreshold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).DeleteThreshold(ctx, req.(*DeleteThresholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_GetActiveAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).GetActiveAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.AlertService/GetActiveAlerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).GetActiveAlerts(ctx, req.(*GetActiveAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_QueryAlertHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryAlertHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlertServiceServer).QueryAlertHistory(m, &alertServiceQueryAlertHistoryServer{stream})
}

type AlertService_QueryAlertHistoryServer interface {
	Send(*QueryAlertHistoryResponse) error
	grpc.ServerStream
}

type alertServiceQueryAlertHistoryServer struct {
	grpc.ServerStream
}

func (x *alertServiceQueryAlertHistoryServer) Send(m *QueryAlertHistoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AlertService_SilenceAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SilenceAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).SilenceAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.AlertService/SilenceAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).SilenceAlert(ctx, req.(*SilenceAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_GetSilenceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSilenceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).GetSilenceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.AlertService/GetSilenceState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).GetSilenceState(ctx, req.(*GetSilenceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_ClearSilence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSilenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).ClearSilence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.AlertService/ClearSilence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).ClearSilence(ctx, req.(*ClearSilenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_GetAlertStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).GetAlertStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.AlertService/GetAlertStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).GetAlertStats(ctx, req.(*GetAlertStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertService_ServiceDesc is the grpc.ServiceDesc for AlertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fieldpulse.api.AlertService",
	HandlerType: (*AlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateThreshold",
			Handler:    _AlertService_CreateThreshold_Handler,
		},
		{
			MethodName: "GetThresholds",
			Handler:    _AlertService_GetThresholds_Handler,
		},
		{
			MethodName: "UpdateThreshold",
			Handler:    _AlertService_UpdateThreshold_Handler,
		},
		{
			MethodName: "DeleteThreshold",
			Handler:    _AlertService_DeleteThreshold_Handler,
		},
		{
			MethodName: "GetActiveAlerts",
			Handler:    _AlertService_GetActiveAlerts_Handler,
		},
		{
			MethodName: "SilenceAlert",
			Handler:    _AlertService_SilenceAlert_Handler,
		},
		{
			MethodName: "GetSilenceState",
			Handler:    _AlertService_GetSilenceState_Handler,
		},
		{
			MethodName: "ClearSilence",
			Handler:    _AlertService_ClearSilence_Handler,
		},
		{
			MethodName: "GetAlertStats",
			Handler:    _AlertService_GetAlertStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryAlertHistory",
			Handler:       _AlertService_QueryAlertHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/alert.proto",
}
