# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import device_pb2 as device__pb2


class DeviceServiceStub(object):
    """DeviceService manages device provisioning, registration, and lifecycle
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDevice = channel.unary_unary(
                '/fieldpulse.api.DeviceService/CreateDevice',
                request_serializer=device__pb2.CreateDeviceRequest.SerializeToString,
                response_deserializer=device__pb2.CreateDeviceResponse.FromString,
                )
        self.GetDevice = channel.unary_unary(
                '/fieldpulse.api.DeviceService/GetDevice',
                request_serializer=device__pb2.GetDeviceRequest.SerializeToString,
                response_deserializer=device__pb2.GetDeviceResponse.FromString,
                )
        self.ListDevices = channel.unary_unary(
                '/fieldpulse.api.DeviceService/ListDevices',
                request_serializer=device__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=device__pb2.ListDevicesResponse.FromString,
                )
        self.UpdateDeviceStatus = channel.unary_unary(
                '/fieldpulse.api.DeviceService/UpdateDeviceStatus',
                request_serializer=device__pb2.UpdateDeviceStatusRequest.SerializeToString,
                response_deserializer=device__pb2.UpdateDeviceStatusResponse.FromString,
                )


class DeviceServiceServicer(object):
    """DeviceService manages device provisioning, registration, and lifecycle
    """

    def CreateDevice(self, request, context):
        """CreateDevice provisions a new device with full certificate bundle
        Server generates keypair, signs certificate, returns connection credentials
        Device is ready to connect immediately after receiving response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevice(self, request, context):
        """GetDevice retrieves device information including certificate metadata
        Uses strong consistency: always reads from PostgreSQL, then warms cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """ListDevices returns paginated device list with optional filtering
        Strong consistency: always reads from PostgreSQL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDeviceStatus(self, request, context):
        """UpdateDeviceStatus marks device as active/silent/degraded/inactive
        Updates PostgreSQL immediately, then invalidates cache
        Alerts other services via MQTT event
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDevice,
                    request_deserializer=device__pb2.CreateDeviceRequest.FromString,
                    response_serializer=device__pb2.CreateDeviceResponse.SerializeToString,
            ),
            'GetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevice,
                    request_deserializer=device__pb2.GetDeviceRequest.FromString,
                    response_serializer=device__pb2.GetDeviceResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=device__pb2.ListDevicesRequest.FromString,
                    response_serializer=device__pb2.ListDevicesResponse.SerializeToString,
            ),
            'UpdateDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDeviceStatus,
                    request_deserializer=device__pb2.UpdateDeviceStatusRequest.FromString,
                    response_serializer=device__pb2.UpdateDeviceStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fieldpulse.api.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """DeviceService manages device provisioning, registration, and lifecycle
    """

    @staticmethod
    def CreateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fieldpulse.api.DeviceService/CreateDevice',
            device__pb2.CreateDeviceRequest.SerializeToString,
            device__pb2.CreateDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fieldpulse.api.DeviceService/GetDevice',
            device__pb2.GetDeviceRequest.SerializeToString,
            device__pb2.GetDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fieldpulse.api.DeviceService/ListDevices',
            device__pb2.ListDevicesRequest.SerializeToString,
            device__pb2.ListDevicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fieldpulse.api.DeviceService/UpdateDeviceStatus',
            device__pb2.UpdateDeviceStatusRequest.SerializeToString,
            device__pb2.UpdateDeviceStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
