// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/proto/telemetry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	// SubmitMetric ingests a single metric point from a device.
	//
	// Validates device existence, persists to TimescaleDB, and invalidates
	// relevant cache entries. Server assigns canonical timestamp for ordering.
	//
	// Errors:
	//   - INVALID_ARGUMENT: device_id not found, value out of range, invalid metric_name
	//   - INTERNAL: database error, cache error
	SubmitMetric(ctx context.Context, in *SubmitMetricRequest, opts ...grpc.CallOption) (*SubmitMetricResponse, error)
	// SubmitBatch ingests multiple metrics atomically.
	//
	// All metrics succeed or all fail. Faster than repeated SubmitMetric calls.
	// Useful for syncing buffered readings from devices.
	//
	// Errors:
	//   - INVALID_ARGUMENT: empty batch, invalid metric in batch
	//   - INTERNAL: database error
	SubmitBatch(ctx context.Context, in *SubmitBatchRequest, opts ...grpc.CallOption) (*SubmitBatchResponse, error)
	// QueryMetrics retrieves raw metric points (server-side streaming).
	//
	// Returns paginated results ordered by timestamp. Streaming provides
	// low-latency access to first result without loading entire result set.
	// Useful for dashboards and real-time analysis.
	//
	// Errors:
	//   - INVALID_ARGUMENT: invalid time range, limit out of bounds
	//   - NOT_FOUND: device or metric doesn't exist
	//   - DEADLINE_EXCEEDED: query timeout
	QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (TelemetryService_QueryMetricsClient, error)
	// GetAggregations retrieves pre-calculated metric aggregations.
	//
	// Returns statistics grouped by time windows (1m/5m/1h/1d). Much faster
	// than raw queries for dashboards and historical trending. Results often
	// cached by TimescaleDB continuous aggregates.
	//
	// Errors:
	//   - INVALID_ARGUMENT: invalid time range
	//   - NOT_FOUND: device or metric doesn't exist
	GetAggregations(ctx context.Context, in *GetAggregationsRequest, opts ...grpc.CallOption) (*GetAggregationsResponse, error)
	// GetMetricStats retrieves summary statistics for a metric.
	//
	// Returns min/max/avg/stddev across all readings (or filtered time range).
	// Useful for anomaly detection and parameter tuning.
	//
	// Errors:
	//   - INVALID_ARGUMENT: invalid time range
	//   - NOT_FOUND: device or metric doesn't exist
	GetMetricStats(ctx context.Context, in *GetMetricStatsRequest, opts ...grpc.CallOption) (*GetMetricStatsResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) SubmitMetric(ctx context.Context, in *SubmitMetricRequest, opts ...grpc.CallOption) (*SubmitMetricResponse, error) {
	out := new(SubmitMetricResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.TelemetryService/SubmitMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) SubmitBatch(ctx context.Context, in *SubmitBatchRequest, opts ...grpc.CallOption) (*SubmitBatchResponse, error) {
	out := new(SubmitBatchResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.TelemetryService/SubmitBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (TelemetryService_QueryMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TelemetryService_ServiceDesc.Streams[0], "/fieldpulse.api.TelemetryService/QueryMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &telemetryServiceQueryMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TelemetryService_QueryMetricsClient interface {
	Recv() (*QueryMetricsResponse, error)
	grpc.ClientStream
}

type telemetryServiceQueryMetricsClient struct {
	grpc.ClientStream
}

func (x *telemetryServiceQueryMetricsClient) Recv() (*QueryMetricsResponse, error) {
	m := new(QueryMetricsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *telemetryServiceClient) GetAggregations(ctx context.Context, in *GetAggregationsRequest, opts ...grpc.CallOption) (*GetAggregationsResponse, error) {
	out := new(GetAggregationsResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.TelemetryService/GetAggregations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetMetricStats(ctx context.Context, in *GetMetricStatsRequest, opts ...grpc.CallOption) (*GetMetricStatsResponse, error) {
	out := new(GetMetricStatsResponse)
	err := c.cc.Invoke(ctx, "/fieldpulse.api.TelemetryService/GetMetricStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility
type TelemetryServiceServer interface {
	// SubmitMetric ingests a single metric point from a device.
	//
	// Validates device existence, persists to TimescaleDB, and invalidates
	// relevant cache entries. Server assigns canonical timestamp for ordering.
	//
	// Errors:
	//   - INVALID_ARGUMENT: device_id not found, value out of range, invalid metric_name
	//   - INTERNAL: database error, cache error
	SubmitMetric(context.Context, *SubmitMetricRequest) (*SubmitMetricResponse, error)
	// SubmitBatch ingests multiple metrics atomically.
	//
	// All metrics succeed or all fail. Faster than repeated SubmitMetric calls.
	// Useful for syncing buffered readings from devices.
	//
	// Errors:
	//   - INVALID_ARGUMENT: empty batch, invalid metric in batch
	//   - INTERNAL: database error
	SubmitBatch(context.Context, *SubmitBatchRequest) (*SubmitBatchResponse, error)
	// QueryMetrics retrieves raw metric points (server-side streaming).
	//
	// Returns paginated results ordered by timestamp. Streaming provides
	// low-latency access to first result without loading entire result set.
	// Useful for dashboards and real-time analysis.
	//
	// Errors:
	//   - INVALID_ARGUMENT: invalid time range, limit out of bounds
	//   - NOT_FOUND: device or metric doesn't exist
	//   - DEADLINE_EXCEEDED: query timeout
	QueryMetrics(*QueryMetricsRequest, TelemetryService_QueryMetricsServer) error
	// GetAggregations retrieves pre-calculated metric aggregations.
	//
	// Returns statistics grouped by time windows (1m/5m/1h/1d). Much faster
	// than raw queries for dashboards and historical trending. Results often
	// cached by TimescaleDB continuous aggregates.
	//
	// Errors:
	//   - INVALID_ARGUMENT: invalid time range
	//   - NOT_FOUND: device or metric doesn't exist
	GetAggregations(context.Context, *GetAggregationsRequest) (*GetAggregationsResponse, error)
	// GetMetricStats retrieves summary statistics for a metric.
	//
	// Returns min/max/avg/stddev across all readings (or filtered time range).
	// Useful for anomaly detection and parameter tuning.
	//
	// Errors:
	//   - INVALID_ARGUMENT: invalid time range
	//   - NOT_FOUND: device or metric doesn't exist
	GetMetricStats(context.Context, *GetMetricStatsRequest) (*GetMetricStatsResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTelemetryServiceServer struct {
}

func (UnimplementedTelemetryServiceServer) SubmitMetric(context.Context, *SubmitMetricRequest) (*SubmitMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitMetric not implemented")
}
func (UnimplementedTelemetryServiceServer) SubmitBatch(context.Context, *SubmitBatchRequest) (*SubmitBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBatch not implemented")
}
func (UnimplementedTelemetryServiceServer) QueryMetrics(*QueryMetricsRequest, TelemetryService_QueryMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryMetrics not implemented")
}
func (UnimplementedTelemetryServiceServer) GetAggregations(context.Context, *GetAggregationsRequest) (*GetAggregationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAggregations not implemented")
}
func (UnimplementedTelemetryServiceServer) GetMetricStats(context.Context, *GetMetricStatsRequest) (*GetMetricStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricStats not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_SubmitMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).SubmitMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.TelemetryService/SubmitMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).SubmitMetric(ctx, req.(*SubmitMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_SubmitBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).SubmitBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.TelemetryService/SubmitBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).SubmitBatch(ctx, req.(*SubmitBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_QueryMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelemetryServiceServer).QueryMetrics(m, &telemetryServiceQueryMetricsServer{stream})
}

type TelemetryService_QueryMetricsServer interface {
	Send(*QueryMetricsResponse) error
	grpc.ServerStream
}

type telemetryServiceQueryMetricsServer struct {
	grpc.ServerStream
}

func (x *telemetryServiceQueryMetricsServer) Send(m *QueryMetricsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TelemetryService_GetAggregations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAggregationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetAggregations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.TelemetryService/GetAggregations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetAggregations(ctx, req.(*GetAggregationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetMetricStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetMetricStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fieldpulse.api.TelemetryService/GetMetricStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetMetricStats(ctx, req.(*GetMetricStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fieldpulse.api.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitMetric",
			Handler:    _TelemetryService_SubmitMetric_Handler,
		},
		{
			MethodName: "SubmitBatch",
			Handler:    _TelemetryService_SubmitBatch_Handler,
		},
		{
			MethodName: "GetAggregations",
			Handler:    _TelemetryService_GetAggregations_Handler,
		},
		{
			MethodName: "GetMetricStats",
			Handler:    _TelemetryService_GetMetricStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryMetrics",
			Handler:       _TelemetryService_QueryMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/telemetry.proto",
}
